apiVersion: cloudwatch.aws.amazon.com/v1alpha1
kind: AmazonCloudWatchAgent
metadata:
  name: cloudwatch-agent
  namespace: amazon-cloudwatch
spec:
  mode: daemonset
  serviceAccount: cloudwatch-agent
  image: 506463145083.dkr.ecr.us-west-2.amazonaws.com/apm-beta-release:latest
  config: |
    {
      "agent": {
        "region": "us-west-2",
        "debug": true
      },
      "traces": {
        "traces_collected": {
          "apm": {
            "enabled": true
          }
        }
      },
      "logs": {
        "metrics_collected": {
          "apm": {
            "enabled": true
          }
        }
      }
    }
  volumeMounts:
    - mountPath: /rootfs
      name: rootfs
      readOnly: true
    - mountPath: /var/run/docker.sock
      name: dockersock
      readOnly: true
    - mountPath: /run/containerd/containerd.sock
      name: containerdsock
    - mountPath: /var/lib/docker
      name: varlibdocker
      readOnly: true
    - mountPath: /sys
      name: sys
      readOnly: true
    - mountPath: /dev/disk
      name: devdisk
      readOnly: true
  volumes:
    - name: rootfs
      hostPath:
        path: /
    - hostPath:
        path: /var/run/docker.sock
      name: dockersock
    - hostPath:
        path: /var/lib/docker
      name: varlibdocker
    - hostPath:
        path: /run/containerd/containerd.sock
      name: containerdsock
    - hostPath:
        path: /sys
      name: sys
    - hostPath:
        path: /dev/disk/
      name: devdisk
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: HOST_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace