apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dcgm-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "amazon-cloudwatch-observability.labels" . | nindent 4}}
