apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "amazon-cloudwatch-observability.labels" . | nindent 4}}
  name: {{ template "amazon-cloudwatch-observability.managerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
