
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: amazon-cloudwatch
spec:
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    app.kubernetes.io/name: amazon-cloudwatch-agent-operator
    control-plane: controller-manager
