kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agent-role-binding
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: amazon-cloudwatch
roleRef:
  kind: ClusterRole
  name: agent-role
  apiGroup: rbac.authorization.k8s.io