apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuron-monitor-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["neuron-monitor-config-map"]
    verbs: ["get"]
