# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: amazoncloudwatchagents.cloudwatch.aws.amazon.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: system
          name: amazon-cloudwatch-webhook-service
          path: /convert
      conversionReviewVersions:
        - v1alpha1
        - v1beta1