# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/cloudwatch.aws.amazon.com_amazoncloudwatchagents.yaml
- bases/cloudwatch.aws.amazon.com_instrumentations.yaml
- bases/cloudwatch.aws.amazon.com_dcgmexporters.yaml
- bases/cloudwatch.aws.amazon.com_neuronmonitors.yaml