# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: Build and Upload Integration Test Artifact
on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  BuildAndUpload:
    uses: ./.github/workflows/build-and-upload-release.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      release: false
      tag: 'integration-test'