name: 'Operator Build Args'
on:
  workflow_call:
    outputs:
      build_args:
        description: "Common build arguments for operator"
        value: |
          VERSION_PKG=${{ env.VERSION_PKG }}
          VERSION=${{ inputs.tag }}
          VERSION_DATE=${{ env.VERSION_DATE }}
          AGENT_VERSION=${{ env.AGENT_VERSION }}
          AUTO_INSTRUMENTATION_JAVA_VERSION=${{ env.AUTO_INSTRUMENTATION_JAVA_VERSION }}
          AUTO_INSTRUMENTATION_PYTHON_VERSION=${{ env.AUTO_INSTRUMENTATION_PYTHON_VERSION }}
          AUTO_INSTRUMENTATION_DOTNET_VERSION=${{ env.AUTO_INSTRUMENTATION_DOTNET_VERSION }}
          AUTO_INSTRUMENTATION_NODEJS_VERSION=${{ env.AUTO_INSTRUMENTATION_NODEJS_VERSION }}
          DCMG_EXPORTER_VERSION=${{ env.DCMG_EXPORTER_VERSION }}
          NEURON_MONITOR_VERSION=${{ env.NEURON_MONITOR_VERSION }}
          TARGET_ALLOCATOR_VERSION=${{ env.TARGET_ALLOCATOR_VERSION }}