# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: PR Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main*
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Unit Test
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true

  lint:
    name: Code standards (linting)
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "~1.23.0"

    - name: Cache tools
      uses: actions/cache@v4
      id: setup-go
      with:
        path: bin
        key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Makefile') }}-${{ steps.setup-go.outputs.go-version }}

    - uses: actions/cache@v4
      with:
        path: |
          /home/runner/.cache/golangci-lint
        key: golangcilint-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          golangcilint-

    - name: Lint
      run: make lint